export interface Movie {
    id: number;
    title: string;
    image: string;
    imageLandscape: string,
    rating: string;
    ageRating: string;
    episodes?: string;
    duration?: string;
    genres: string[];
    description: string;
    isNewEpisode?: boolean;
    isPremium?: boolean;
    isTop10?: boolean;
}

export const CONTINUE_WATCHING_MOVIES: Movie[] = [
    {
        id: 1,
        title: "Don't Look Up",
        image: "src/assets/landscape/dont-look-up.png",
        imageLandscape: "src/assets/landscape/dont-look-up.png",
        rating: "4.5/5",
        ageRating: "13+",
        duration: "2j 33m",
        genres: ["Komedi", "Drama", "Sci-Fi"],
        description: "Dua astronom tingkat rendah harus melakukan tur media raksasa untuk memperingatkan umat manusia tentang komet yang mendekat yang akan menghancurkan planet Bumi.",
    },
    {
        id: 2,
        title: "All of Us Are Dead",
        image: "src/assets/landscape/all-of-us-are-dead.png",
        imageLandscape: "src/assets/landscape/all-of-us-are-dead.png",
        rating: "4.2/5",
        ageRating: "18+",
        episodes: "12 Episode",
        genres: ["Horor", "Aksi", "Drama"],
        description: "Sekelompok siswa terjebak di sekolah menengah mereka saat wabah virus zombie merebak. Mereka harus berjuang untuk bertahan hidup atau menjadi salah satu dari yang terinfeksi.",
        isTop10: true
    },
    {
        id: 3,
        title: "Blue Lock",
        image: "src/assets/landscape/blue-lock.png",
        imageLandscape: "src/assets/landscape/blue-lock.png",
        rating: "4.6/5",
        ageRating: "13+",
        episodes: "24 Episode",
        genres: ["Animasi", "Olahraga", "Drama"],
        description: "Keinginan Jepang untuk kejayaan Piala Dunia membawa Federasi Sepak Bola Jepang meluncurkan program pelatihan baru yang radikal untuk menemukan striker egois terbaik.",
        isNewEpisode: true,
    },
    {
        id: 4,
        title: "A Man Called Otto",
        image: "src/assets/landscape/otto.png",
        imageLandscape: "src/assets/landscape/otto.png",
        rating: "4.4/5",
        ageRating: "13+",
        duration: "2j 33m",
        genres: ["Komedi", "Drama"],
        description: "Otto adalah seorang pria pemarah yang menyerah pada kehidupan setelah kehilangan istrinya. Segalanya berubah ketika sebuah keluarga muda yang lincah pindah ke sebelah rumahnya.",
    },
    {
        id: 5,
        title: "The Tomorrow War",
        image: "src/assets/landscape/tomorrow-war.png",
        imageLandscape: "src/assets/landscape/tomorrow-war.png",
        rating: "4.5/5",
        ageRating: "18+",
        duration: "2j 33m",
        genres: ["Aksi", "Sci-Fi", "Petualangan"],
        description: "Seorang pria dari masa lalu dipanggil ke masa depan untuk membantu memenangkan perang melawan alien.",
        isTop10: true
    },
];

export const TOP_RATING_MOVIES: Movie[] = [
    {
        id: 6,
        title: "Suzume",
        image: "src/assets/portrait/suzume.png",
        imageLandscape: "src/assets/landscape/suzume.png",
        rating: "4.9/5",
        ageRating: "SU",
        duration: "2j 33m",
        genres: ["Animasi", "Fantasi", "Petualangan"],
        description: "Seorang gadis remaja berusia 17 tahun bernama Suzume membantu seorang pemuda misterius menutup pintu-pintu yang melepaskan bencana di seluruh Jepang.",
        isNewEpisode: true,
    },
    {
        id: 6,
        title: "Suzume",
        image: "src/assets/portrait/suzume.png",
        imageLandscape: "src/assets/landscape/suzume.png",
        rating: "4.9/5",
        ageRating: "SU",
        duration: "2j 33m",
        genres: ["Animasi", "Fantasi", "Petualangan"],
        description: "Seorang gadis remaja berusia 17 tahun bernama Suzume membantu seorang pemuda misterius menutup pintu-pintu yang melepaskan bencana di seluruh Jepang.",
        isNewEpisode: true,
    },
    {
        id: 6,
        title: "Suzume",
        image: "src/assets/portrait/suzume.png",
        imageLandscape: "src/assets/landscape/suzume.png",
        rating: "4.9/5",
        ageRating: "SU",
        duration: "2j 33m",
        genres: ["Animasi", "Fantasi", "Petualangan"],
        description: "Seorang gadis remaja berusia 17 tahun bernama Suzume membantu seorang pemuda misterius menutup pintu-pintu yang melepaskan bencana di seluruh Jepang.",
        isNewEpisode: true,
    },
    {
        id: 7,
        title: "Jurassic World Dominion",
        image: "src/assets/portrait/jurassic-world.png",
        imageLandscape: "src/assets/landscape/jurassic-world.png",
        rating: "4.0/5",
        ageRating: "13+",
        duration: "2j 33m",
        genres: ["Aksi", "Petualangan", "Sci-Fi"],
        description: "Empat tahun setelah kehancuran Pulau Nublar, dinosaurus sekarang hidup—dan berburu—bersama manusia di seluruh dunia.",
        isNewEpisode: false,
        isPremium: false
    },
    {
        id: 8,
        title: "Sonic the Hedgehog 2",
        image: "src/assets/portrait/sonic-2.png",
        imageLandscape: "src/assets/landscape/sonic-2.png",
        rating: "4.7/5",
        ageRating: "SU",
        duration: "2j 33m",
        genres: ["Aksi", "Komedi", "Petualangan"],
        description: "Setelah menetap di Green Hills, Sonic ingin membuktikan bahwa dia memiliki apa yang diperlukan untuk menjadi pahlawan sejati.",
        isNewEpisode: false,
        isPremium: false
    },
    {
        id: 9,
        title: "All of Us Are Dead",
        image: "src/assets/portrait/all-of-us-are-dead.png",
        imageLandscape: "src/assets/landscape/all-of-us-are-dead.png",
        rating: "4.2/5",
        ageRating: "18+",
        episodes: "12 Episode",
        genres: ["Misteri", "Kriminal", "Fantasi"],
        description: "Sekelompok siswa terjebak di sekolah menengah mereka saat wabah virus zombie merebak. Mereka harus berjuang untuk bertahan hidup atau menjadi salah satu dari yang terinfeksi.",
        isTop10: true
    },
    {
        id: 10,
        title: "Big Hero 6",
        image: "src/assets/portrait/big-hero-6.png",
        imageLandscape: "src/assets/landscape/big-hero-6.png",
        rating: "4.8/5",
        ageRating: "SU",
        duration: "2j 33m",
        genres: ["Animasi", "Aksi", "Komedi"],
        description: "Seorang jenius teknologi muda bersama robot medisnya membentuk tim superhero untuk menyelamatkan kota.",
        isNewEpisode: false,
        isPremium: false,
    }
];

export const TRENDING_MOVIES: Movie[] = [
    {
        id: 11,
        title: "The Tomorrow War",
        image: "src/assets/portrait/tomorrow-war.png",
        imageLandscape: "src/assets/landscape/tomorrow-war.png",
        rating: "4.5/5",
        ageRating: "18+",
        duration: "2j 33m",
        genres: ["Aksi", "Sci-Fi", "Petualangan"],
        description: "Seorang pria dari masa lalu dipanggil ke masa depan untuk membantu memenangkan perang melawan alien.",
        isTop10: true
    },
    {
        id: 12,
        title: "Ant-Man and the Wasp: Quantumania",
        image: "src/assets/portrait/ant-man.png",
        imageLandscape: "src/assets/landscape/ant-man.png",
        rating: "4.2/5",
        ageRating: "13+",
        duration: "2j 33m",
        genres: ["Aksi", "Komedi", "Sci-Fi"],
        description: "Scott Lang dan Hope van Dyne menjelajahi Alam Kuantum dan menghadapi Kang the Conqueror.",
        isTop10: true
    },
    {
        id: 13,
        title: "Guardians of the Galaxy Vol. 3",
        image: "src/assets/portrait/gotg-3.png",
        imageLandscape: "src/assets/landscape/gotg-3.png",
        rating: "4.8/5",
        ageRating: "13+",
        duration: "2j 33m",
        genres: ["Aksi", "Petualangan", "Sci-Fi"],
        description: "Para penjaga galaksi harus bersatu untuk menyelamatkan salah satu anggota mereka dalam misi berbahaya.",
        isTop10: true
    },
    {
        id: 14,
        title: "A Man Called Otto",
        image: "src/assets/portrait/otto.png",
        imageLandscape: "src/assets/landscape/otto.png",
        rating: "4.4/5",
        ageRating: "13+",
        duration: "2j 33m",
        genres: ["Drama", "Komedi"],
        description: "Kisah seorang pria pemarah yang hidupnya berubah setelah tetangga baru yang ceria pindah ke sebelah rumahnya.",
        isTop10: true
    },
    {
        id: 15,
        title: "The Little Mermaid",
        image: "src/assets/portrait/little-mermaid.png",
        imageLandscape: "src/assets/landscape/little-mermaid.png",
        rating: "4.0/5",
        ageRating: "SU",
        duration: "2j 33m",
        genres: ["Fantasi", "Musikal", "Petualangan"],
        description: "Ariel, seorang putri duyung muda, membuat kesepakatan dengan penyihir laut untuk menjadi manusia.",
        isTop10: true
    }
];

export const NEW_RELEASE_MOVIES: Movie[] = [
    {
        id: 16,
        title: "The Little Mermaid",
        image: "src/assets/portrait/little-mermaid.png",
        imageLandscape: "src/assets/landscape/little-mermaid.png",
        rating: "4.0/5",
        ageRating: "SU",
        duration: "2j 33m",
        genres: ["Fantasi", "Musikal", "Petualangan"],
        description: "Ariel, seorang putri duyung muda, membuat kesepakatan dengan penyihir laut untuk menjadi manusia.",
        isTop10: true
    },
    {
        id: 17,
        title: "Duty After School",
        image: "src/assets/portrait/duty-after-school.png",
        imageLandscape: "src/assets/landscape/duty-after-school.png",
        rating: "4.6/5",
        ageRating: "18+",
        episodes: "10 Episode",
        genres: ["Aksi", "Thriller", "Drama"],
        description: "Sebuah benda tak dikenal mengambil alih dunia. Dalam keputusasaan, Departemen Pertahanan mulai merekrut lebih banyak tentara, termasuk siswa sekolah menengah. Mereka pun segera menjadi pejuang garis depan dalam perang.",
        isNewEpisode: true
    },
    {
        id: 18,
        title: "Big Hero 6",
        image: "src/assets/portrait/big-hero-6.png",
        imageLandscape: "src/assets/landscape/big-hero-6.png",
        rating: "4.7/5",
        ageRating: "SU",
        duration: "2j 33m",
        genres: ["Animasi", "Aksi", "Petualangan"],
        description: "Seorang jenius teknologi muda bersama robot medisnya membentuk tim superhero untuk menyelamatkan kota.",
    },
    {
        id: 19,
        title: "All of Us Are Dead",
        image: "src/assets/portrait/all-of-us-are-dead.png",
        imageLandscape: "src/assets/landscape/all-of-us-are-dead.png",
        rating: "4.3/5",
        ageRating: "18+",
        episodes: "12 Episode",
        genres: ["Horor", "Aksi", "Thriller"],
        description: "Sekelompok siswa terjebak di sekolah menengah mereka saat wabah virus zombie merebak. Mereka harus berjuang untuk bertahan hidup atau menjadi salah satu dari yang terinfeksi.",
        isTop10: true
    },
    {
        id: 20,
        title: "Missing",
        image: "src/assets/portrait/missing.png",
        imageLandscape: "src/assets/landscape/missing.png",
        rating: "4.5/5",
        ageRating: "13+",
        duration: "2j 33m",
        genres: ["Misteri", "Thriller"],
        description: "Seorang gadis remaja menggunakan teknologi digital untuk mencari ibunya yang hilang saat berlibur di Kolombia.",
        isNewEpisode: false
    }
];

export const CONTINUE_WATCHING_SERIES: Movie[] = [
    {
        id: 21,
        title: "Alice in Borderland",
        image: "src/assets/landscape/alice-in-borderland.png",
        imageLandscape: "src/assets/landscape/alice-in-borderland.png",
        rating: "4.5/5",
        ageRating: "18+",
        episodes: "8 Episode",
        genres: ["Aksi", "Misteri", "Thriller"],
        description: "Seorang gamer pengangguran dan teman-temannya mendapati diri mereka berada di Tokyo yang kosong, di mana mereka harus mengikuti permainan berbahaya untuk bertahan hidup.",
        isNewEpisode: true,
    },
    {
        id: 22,
        title: "My Perfect Stranger",
        image: "src/assets/landscape/my-perfect-stranger.png",
        imageLandscape: "src/assets/landscape/my-perfect-stranger.png",
        rating: "4.6/5",
        ageRating: "13+",
        episodes: "16 Episode",
        genres: ["Misteri", "Romantis", "Drama"],
        description: "Yoon Hae-joon dan Baek Yoon-young melakukan perjalanan kembali ke tahun 1987 untuk memecahkan serangkaian kasus pembunuhan misterius.",
        isNewEpisode: true,
    },
    {
        id: 23,
        title: "All of Us Are Dead",
        image: "src/assets/portrait/all-of-us-are-dead.png",
        imageLandscape: "src/assets/landscape/all-of-us-are-dead.png",
        rating: "4.2/5",
        ageRating: "18+",
        episodes: "12 Episode",
        genres: ["Misteri", "Kriminal", "Fantasi"],
        description: "Sekelompok siswa terjebak di sekolah menengah mereka saat wabah virus zombie merebak. Mereka harus berjuang untuk bertahan hidup atau menjadi salah satu dari yang terinfeksi.",
        isPremium: true,
        isTop10: true,
    },
    {
        id: 24,
        title: "Ted Lasso",
        image: "src/assets/landscape/ted-lasso.png",
        imageLandscape: "src/assets/landscape/ted-lasso.png",
        rating: "4.4/5",
        ageRating: "13+",
        episodes: "34 Episode",
        genres: ["Komedi", "Drama", "Olahraga"],
        description: "Pelatih sepak bola Amerika, Ted Lasso, pindah ke Inggris untuk melatih tim sepak bola Liga Utama Inggris yang sedang kesulitan.",
        isNewEpisode: true,
    },
    {
        id: 25,
        title: "Duty After School",
        image: "src/assets/portrait/duty-after-school.png",
        imageLandscape: "src/assets/landscape/duty-after-school.png",
        rating: "4.5/5",
        ageRating: "18+",
        episodes: "10 Episode",
        genres: ["Aksi", "Misteri", "Thriller"],
        description: "Sebuah benda tak dikenal mengambil alih dunia. Dalam keputusasaan, Departemen Pertahanan mulai merekrut lebih banyak tentara, termasuk siswa sekolah menengah. Mereka pun segera menjadi pejuang garis depan dalam perang.",
        isPremium: true,
    },
];

export const CHILL_EXCLUSIVE_MOVIES: Movie[] = [
    {
        id: 26,
        title: "The Little Mermaid",
        image: "src/assets/portrait/little-mermaid.png",
        imageLandscape: "src/assets/landscape/little-mermaid.png",
        rating: "4.8/5",
        ageRating: "SU",
        duration: "2j 33m",
        genres: ["Fantasi", "Petualangan", "Romantis"],
        description: "Ariel, seorang putri duyung muda, membuat kesepakatan dengan penyihir laut untuk menjadi manusia.",
        isPremium: true,
        isTop10: true,
    },
    {
        id: 27,
        title: "Duty After School",
        image: "src/assets/portrait/duty-after-school.png",
        imageLandscape: "src/assets/landscape/duty-after-school.png",
        rating: "4.5/5",
        ageRating: "18+",
        episodes: "10 Episode",
        genres: ["Aksi", "Misteri", "Thriller"],
        description: "Sebuah benda tak dikenal mengambil alih dunia. Dalam keputusasaan, Departemen Pertahanan mulai merekrut lebih banyak tentara, termasuk siswa sekolah menengah. Mereka pun segera menjadi pejuang garis depan dalam perang.",
        isPremium: true,
    },
    {
        id: 28,
        title: "Big Hero 6",
        image: "src/assets/portrait/big-hero-6.png",
        imageLandscape: "src/assets/landscape/big-hero-6.png",
        rating: "4.9/5",
        ageRating: "SU",
        duration: "2j 33m",
        genres: ["Animasi", "Aksi", "Petualangan"],
        description: "Seorang jenius teknologi muda bersama robot medisnya membentuk tim superhero untuk menyelamatkan kota.",
        isPremium: true,
    },
    {
        id: 29,
        title: "All of Us Are Dead",
        image: "src/assets/portrait/all-of-us-are-dead.png",
        imageLandscape: "src/assets/landscape/all-of-us-are-dead.png",
        rating: "4.2/5",
        ageRating: "18+",
        episodes: "12 Episode",
        genres: ["Misteri", "Kriminal", "Fantasi"],
        description: "Sekelompok siswa terjebak di sekolah menengah mereka saat wabah virus zombie merebak. Mereka harus berjuang untuk bertahan hidup atau menjadi salah satu dari yang terinfeksi.",
        isPremium: true,
        isTop10: true,
    },
    {
        id: 30,
        title: "Missing",
        image: "src/assets/portrait/missing.png",
        imageLandscape: "src/assets/landscape/missing.png",
        rating: "4.7/5",
        ageRating: "13+",
        duration: "2j 33m",
        genres: ["Misteri", "Thriller"],
        description: "Seorang gadis remaja menggunakan teknologi digital untuk mencari ibunya yang hilang saat berlibur di Kolombia.",
        isPremium: true,
    }
];

export const MY_LIST_MOVIES: Movie[] = [
    {
        id: 31,
        title: "The Little Mermaid",
        image: "src/assets/portrait/little-mermaid.png",
        imageLandscape: "src/assets/landscape/little-mermaid.png",
        rating: "4.8/5",
        ageRating: "SU",
        duration: "2j 33m",
        genres: ["Fantasi", "Petualangan", "Romantis"],
        description: "Ariel, seorang putri duyung muda, membuat kesepakatan dengan penyihir laut untuk menjadi manusia.",
        isPremium: true,
        isTop10: true,
    },
    {
        id: 32,
        title: "Duty After School",
        image: "src/assets/portrait/duty-after-school.png",
        imageLandscape: "src/assets/landscape/duty-after-school.png",
        rating: "4.5/5",
        ageRating: "18+",
        episodes: "10 Episode",
        genres: ["Aksi", "Misteri", "Thriller"],
        description: "Sebuah benda tak dikenal mengambil alih dunia. Dalam keputusasaan, Departemen Pertahanan mulai merekrut lebih banyak tentara, termasuk siswa sekolah menengah. Mereka pun segera menjadi pejuang garis depan dalam perang.",
        isPremium: true,
    },
    {
        id: 33,
        title: "Big Hero 6",
        image: "src/assets/portrait/big-hero-6.png",
        imageLandscape: "src/assets/landscape/big-hero-6.png",
        rating: "4.9/5",
        ageRating: "SU",
        duration: "2j 33m",
        genres: ["Animasi", "Aksi", "Petualangan"],
        description: "Seorang jenius teknologi muda bersama robot medisnya membentuk tim superhero untuk menyelamatkan kota.",
        isPremium: true,
    },
    {
        id: 34,
        title: "Alice in Borderland",
        image: "src/assets/portrait/alice-in-borderland.png",
        imageLandscape: "src/assets/landscape/alice-in-borderland.png",
        rating: "4.5/5",
        ageRating: "18+",
        episodes: "8 Episode",
        genres: ["Aksi", "Misteri", "Thriller"],
        description: "Seorang gamer pengangguran dan teman-temannya mendapati diri mereka berada di Tokyo yang kosong, di mana mereka harus mengikuti permainan berbahaya untuk bertahan hidup.",
        isNewEpisode: true,
    },
    {
        id: 35,
        title: "My Perfect Stranger",
        image: "src/assets/portrait/my-perfect-stranger.png",
        imageLandscape: "src/assets/landscape/my-perfect-stranger.png",
        rating: "4.6/5",
        ageRating: "13+",
        episodes: "16 Episode",
        genres: ["Misteri", "Romantis", "Drama"],
        description: "Yoon Hae-joon dan Baek Yoon-young melakukan perjalanan kembali ke tahun 1987 untuk memecahkan serangkaian kasus pembunuhan misterius.",
        isNewEpisode: true,
    },
    {
        id: 36,
        title: "All of Us Are Dead",
        image: "src/assets/portrait/all-of-us-are-dead.png",
        imageLandscape: "src/assets/landscape/all-of-us-are-dead.png",
        rating: "4.2/5",
        ageRating: "18+",
        episodes: "12 Episode",
        genres: ["Misteri", "Kriminal", "Fantasi"],
        description: "Sekelompok siswa terjebak di sekolah menengah mereka saat wabah virus zombie merebak. Mereka harus berjuang untuk bertahan hidup atau menjadi salah satu dari yang terinfeksi.",
        isPremium: true,
        isTop10: true,
    },
    {
        id: 37,
        title: "Missing",
        image: "src/assets/portrait/missing.png",
        imageLandscape: "src/assets/landscape/missing.png",
        rating: "4.7/5",
        ageRating: "13+",
        duration: "2j 33m",
        genres: ["Misteri", "Thriller"],
        description: "Seorang gadis remaja menggunakan teknologi digital untuk mencari ibunya yang hilang saat berlibur di Kolombia.",
        isPremium: true,
    },
    {
        id: 38,
        title: "Suzume",
        image: "src/assets/portrait/suzume.png",
        imageLandscape: "src/assets/landscape/suzume.png",
        rating: "4.9/5",
        ageRating: "SU",
        duration: "2j 33m",
        genres: ["Animasi", "Fantasi", "Petualangan"],
        description: "Seorang gadis remaja berusia 17 tahun bernama Suzume membantu seorang pemuda misterius menutup pintu-pintu yang melepaskan bencana di seluruh Jepang.",
        isNewEpisode: true,
    },
    {
        id: 39,
        title: "Jurassic World Dominion",
        image: "src/assets/portrait/jurassic-world.png",
        imageLandscape: "src/assets/landscape/jurassic-world.png",
        rating: "4.0/5",
        ageRating: "13+",
        duration: "2j 33m",
        genres: ["Aksi", "Petualangan", "Sci-Fi"],
        description: "Empat tahun setelah kehancuran Pulau Nublar, dinosaurus sekarang hidup—dan berburu—bersama manusia di seluruh dunia.",
        isNewEpisode: false,
        isPremium: false
    },
    {
        id: 40,
        title: "Sonic the Hedgehog 2",
        image: "src/assets/portrait/sonic-2.png",
        imageLandscape: "src/assets/landscape/sonic-2.png",
        rating: "4.7/5",
        ageRating: "SU",
        duration: "2j 33m",
        genres: ["Aksi", "Komedi", "Petualangan"],
        description: "Setelah menetap di Green Hills, Sonic ingin membuktikan bahwa dia memiliki apa yang diperlukan untuk menjadi pahlawan sejati.",
        isNewEpisode: false,
        isPremium: false
    },
];